name: Lint

on:
  pull_request:
    branches: [ "main", "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.14.1'
      - name: Run ESLint
        run: npx eslint@10.2.0 "chrome/lib/*.js" --ignore-pattern "**/jquery*.js" --config .eslintrc.json
